### PR TITLE
ref(travis): use travis deploy pipeline

### LINKED ISSUE #28: deis/riak:latest on Docker Hub is broken
The Dockerfile specifies `/bin/boot` as the executable, but that binary is missing from the current `deis/riak:latest` image at Docker Hub. This breaks `helm` CI testing since the [`riak`](https://github.com/helm/charts/tree/master/riak) chart cannot deploy successfully.

### PR DESCRIPTION
**Pull request by bacongobbler**
Building the image requires compiling the Go binaries and copying
them into the root filesystem, which is something Docker's automated
build system does not have the ability to do. Instead, leveraging
Travis' deploy system will allow us to build the image as we see
fit.

closes #28 
closes helm/charts#68
closes helm/charts#69
closes helm/charts#70

TODO:
- [x] disable automated builds on DockerHub
- [x] populate deis/riak repo on travis with DOCKER_EMAIL, DOCKER_USERNAME, DOCKER_PASSWORD, QUAY_EMAIL, QUAY_USERNAME, and QUAY_PASSWORD

### CODE REVIEW

File: _scripts/deploy.sh [hunk 1]
```diff
@@ -0,0 +1,14 @@
+#!/usr/bin/env bash
+#
+# Build and push Docker images to Docker Hub and quay.io.
+#
+
+cd "$(dirname "$0")" || exit 1
+
+cd ..
+
+export IMAGE_PREFIX=deis VERSION=latest
```
Comment (bacongobbler) [inline _scripts/deploy.sh:10]: note that I have made the image prefix to `deis` since this is not a part of the v2-beta effort, and in order to not make any changes in [the helm chart](https://github.com/helm/charts/blob/master/riak/manifests/riak-rc.yaml#L17) I targeted this image as such.

**Comment by arschles** [comment]
@bacongobbler oh! I didn't realize that we were using native DockerHub builds here. Code LGTM :+1:

File: _scripts/deploy.sh (hunk 1 above)
Comment (arschles) [inline _scripts/deploy.sh:10]: :+1:

**Comment by arschles** [comment]
Note that the build status listed here is not representative of what will happen on `master`, because it didn't exercise the deploy logic. We still need `DOCKER_EMAIL`, `DOCKER_USERNAME`, `DOCKER_PASSWORD`, `QUAY_EMAIL`, `QUAY_USERNAME`, and `QUAY_PASSWORD` set in the Travis settings before deploy will work.

cc/ @mboersma @sgoings

**Comment by mboersma** [comment]
>  still need DOCKER_EMAIL, DOCKER_USERNAME, ...

Done.

**Comment by arschles** [comment]
thanks @mboersma !
